import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";
import { Activity, ShieldCheck, AlertCircle, Trash2, TrendingUp } from "lucide-react";
import { motion } from "framer-motion";
import moment from "moment";
import { getHistory, clearHistory } from "@/lib/firebase";

function buildBins(probs) {
  const arr = Array.from({ length: 10 }, (_, i) => ({ name: `${i / 10}`, count: 0 }));
  for (const p of probs) {
    const idx = Math.min(9, Math.floor(p * 10));
    arr[idx].count += 1;
  }
  return arr;
}

function StatCard({ icon: Icon, label, value, color }) {
  const c = color === "violet" ? "text-violet-300" : color === "cyan" ? "text-cyan-300" : "text-slate-100";
  return (
    <div className="glass-card glass-card-hover p-5">
      <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-400/15 to-violet-500/15 border border-white/10 flex items-center justify-center mb-3">
        <Icon className={`w-5 h-5 ${c}`} />
      </div>
      <p className="text-xs text-slate-400">{label}</p>
      <p className="text-2xl font-bold text-slate-50 mt-1">{value}</p>
    </div>
  );
}

export default function Analytics() {
  const qc = useQueryClient();
  const { data, isError } = useQuery({ queryKey: ["history"], queryFn: getHistory });
  const items = data || [];
  const total = items.length;
  const benign = items.filter((i) => i.prediction === 0).length;
  const malignant = items.filter((i) => i.prediction === 1).length;
  const dist = buildBins(items.map((i) => i.probability));
  const clear = useMutation({
    mutationFn: clearHistory,
    onSuccess: () => qc.invalidateQueries({ queryKey: ["history"] }),
  });

  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-center gap-2.5 mb-2">
          <Activity className="w-5 h-5 text-cyan-300" />
          <span className="text-xs uppercase tracking-widest text-cyan-300/80">Analytics</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-bold text-slate-50">Prediction Analytics</h1>
        <p className="text-slate-400 mt-1.5">Real predictions generated by this application.</p>
      </motion.div>

      {isError && (
        <div className="flex items-start gap-2.5 rounded-xl border border-rose-400/25 bg-rose-400/5 px-4 py-3 text-sm text-rose-200">
          <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
          <p>Prediction service unavailable. Start the FastAPI backend on port 8000.</p>
        </div>
      )}

      <div className="grid sm:grid-cols-3 gap-4">
        <StatCard icon={Activity} label="Prediction Count" value={total} />
        <StatCard icon={ShieldCheck} label="Benign Predictions" value={benign} color="cyan" />
        <StatCard icon={TrendingUp} label="Malignant Predictions" value={malignant} color="violet" />
      </div>

      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-5">
        <h3 className="text-sm font-semibold text-slate-200 mb-4">Probability Distribution</h3>
        {total === 0 ? (
          <p className="text-sm text-slate-500 py-8 text-center">
            No predictions yet. Run a prediction to see analytics.
          </p>
        ) : (
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={dist}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" />
              <XAxis dataKey="name" stroke="#64748b" fontSize={11} />
              <YAxis stroke="#64748b" fontSize={11} allowDecimals={false} />
              <Tooltip
                contentStyle={{
                  background: "#0b1120",
                  border: "1px solid rgba(255,255,255,0.1)",
                  borderRadius: 8,
                  fontSize: 12,
                }}
              />
              <Bar dataKey="count" fill="#22d3ee" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        )}
      </motion.div>

      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-5">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-sm font-semibold text-slate-200">Recent Predictions</h3>
          {total > 0 && (
            <button
              onClick={() => clear.mutate()}
              disabled={clear.isPending}
              className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-xs text-slate-300 hover:bg-white/10 transition"
            >
              <Trash2 className="w-3.5 h-3.5" /> Clear History
            </button>
          )}
        </div>
        {total === 0 ? (
          <p className="text-sm text-slate-500 py-6 text-center">No prediction history yet.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-[11px] uppercase tracking-wide text-slate-500 border-b border-white/10">
                  <th className="py-2 pr-4 font-medium">Date/Time</th>
                  <th className="py-2 pr-4 font-medium">Prediction</th>
                  <th className="py-2 pr-4 font-medium">Probability</th>
                  <th className="py-2 font-medium">Model</th>
                </tr>
              </thead>
              <tbody>
                {items.map((it, i) => (
                  <tr key={i} className="border-b border-white/5">
                    <td className="py-2.5 pr-4 text-slate-400">
                      {moment(it.timestamp).format("MMM D, HH:mm:ss")}
                    </td>
                    <td className="py-2.5 pr-4">
                      <span className={it.prediction === 1 ? "text-violet-300" : "text-cyan-300"}>
                        {it.label}
                      </span>
                    </td>
                    <td className="py-2.5 pr-4 text-slate-300">
                      {(it.probability * 100).toFixed(2)}%
                    </td>
                    <td className="py-2.5 text-slate-400 text-xs">{it.model}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </motion.div>
    </div>
  );
}